[build-system]
requires = ["setuptools>=40.8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Zinc.build"
version = "0.2.0.1a3"
description = "A Programming Language called Zinc.build"
requires-python = ">=3.9"
license = { text = "All Rights Reserved" }
dependencies = [
]

[tool.setuptools.packages.find]
where = ["."]
exclude = ["run*"]

[project.scripts]
aurapl = "zincbuild:create_zincbuild_launcher_and_add_to_path"